[sinks.aws_s3]
  # General
  type = "aws_s3" 
  inputs = ["log_json"]
  bucket = "${AWS_BUCKET}" 
  compression = "gzip" 
  region = "${AWS_REGION}"
  framing.method = "newline_delimited"
  encoding.codec = "json"
  key_prefix = "{{fly.app.name}}/%F/" # optional, default
  healthcheck.enabled = true # optional, default
  ${S3_ENDPOINT+endpoint = "$S3_ENDPOINT"}
